version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 7s
      timeout: 30s
      retries: 3
  gateway:
    build: ./src/services/gateway
    container_name: gateway
    restart: always
    environment:
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmq

  
  shoesmicro:
    restart: always 
    depends_on:
      rabbitmq:
        condition: service_healthy
    build: ./src/services/shoes

